#!/bin/sh

case "$1" in
	start)
		if ! mountpoint -q /boot; then
			echo -n "Mount boot: "
			mount /dev/mmcblk0p1 /boot
			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
		fi
		;;
	stop)
		if mountpoint -q /boot; then
			echo -n "Unmount boot: "
			umount /boot
			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
		fi
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 1
		;;
esac

