#!/bin/sh

case "$1" in
	start)
		if ! mountpoint -q /boot && [ -b /dev/mmcblk0p1 ]; then
			echo -n "Mount boot: "
			mount /dev/mmcblk0p1 /boot
			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
		fi

		if [ -f /etc/bootlogo.raw ]; then
			# Use this to generate custom splash images:
			# ffmpeg -i bootlogo.png -f rawvideo -pix_fmt bgra /etc/bootlogo.raw
			cat /etc/bootlogo.raw > /dev/fb0
		fi
		;;
	stop)
		if mountpoint -q /boot; then
			echo -n "Unmount boot: "
			umount /boot
			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
		fi
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 1
		;;
esac

