#!/bin/sh

case "$1" in
	start)
		echo -n "Mount boot: "
		mount /dev/mmcblk0p1 /boot
		[ $? -eq 0 ] && echo "OK" || echo "ERROR"

		# Permit rootfs updates using update.tar.gz
		if [ -f /boot/update.tar.gz ]; then
			if [ -f /pre-update ]; then
				/pre-update
				rm /pre-update
			fi

			gunzip /boot/update.tar.gz -c | tar -xvC / && rm /boot/update.tar.gz

			if [ -f /post-update ]; then
			   /post-update
			   rm /post-update
			fi
		fi

		# Move system files if requested
		if [ -f /boot/dhcpcd.conf ]; then
			mv /boot/dhcpcd.conf
		fi
		if [ -f /boot/wpa_supplicant.conf ]; then
			mv /boot/wpa_supplicant.conf /etc/wpa_supplicant.conf
		fi

		# Enable SSH on demand
		if [ -f /boot/ssh && ! -f /etc/init.d/S50dropbear ]; then
			mv /etc/init.d/50dropbear /etc/init.d/S50dropbear
		fi

		;;
	stop)
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 1
		;;
esac
