#!/bin/sh

UPGRADE_FILE="update.tar.gz"

case "$1" in
	start)
		while true; do
            echo "Checking for $UPGRADE_FILE on USB drives..."
			for MOUNT_POINT in $(echo /media/usb[0-7] 2>/dev/null); do
				if mountpoint -q "$MOUNT_POINT"; then
                    echo "Checking $MOUNT_POINT"
					if [ -f "$MOUNT_POINT/$UPGRADE_FILE" ]; then
                        echo "Found $UPGRADE_FILE on $MOUNT_POINT"
                        cp "$MOUNT_POINT/$UPGRADE_FILE" /boot/$UPGRADE_FILE
                        echo "Copied $UPGRADE_FILE to /boot"
                        /etc/init.d/S02setup start
						rm -f "$MOUNT_POINT/$UPGRADE_FILE"
					fi
					
				fi
			done
			sleep 2
		done &
		;;
	stop)
		killall S03upgrade-monitor
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 1
		;;
esac
