#!/bin/sh

DAEMON=/usr/bin/DuetScreen
DAEMON_OPTS=""
NAME=DuetScreen
PIDFILE=/var/run/$NAME.pid

start() {
	echo -n "Starting $NAME: "
	start-stop-daemon -S -b -q -p $PIDFILE -m -x $DAEMON -- $DAEMON_OPTS
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

stop() {
	echo -n "Stopping $NAME: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
