#!/bin/sh

DAEMON=/usr/sbin/wpa_supplicant
DAEMON_OPTS="-B -i wlan0 -c /etc/wpa_supplicant.conf"
NAME=wpa_supplicant
PIDFILE=/var/run/$NAME.pid
MAX_WAIT=10

start() {
	echo "Starting $NAME..."
	for i in $(seq 1 $MAX_WAIT); do
		if [ -d /sys/class/net/wlan0 ]; then
			break
		fi
		sleep 1
	done
	start-stop-daemon -S -q -x $DAEMON -- -P $PIDFILE $DAEMON_OPTS
}

stop() {
	echo -n "Stopping $NAME: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
