#!/bin/sh

UPGRADE_FILE="update.tar.gz"
PIDFILE="/var/run/S50rootfs-upgrade.pid"

function do_upgrade() {
	FILE="$1"

	# Run pre-update if applicable
	gunzip -c $FILE | tar -xvC / pre-update &> /dev/null || true
	if [ -f /pre-update ]; then
		chmod +x /pre-update
		echo "Running pre-update script..."
		/pre-update $FILE
	fi

	# Extract everything over rootfs and delete pre-update if needed
	gunzip $FILE -c | tar -xvC / > /dev/null && rm -f $FILE
	rm -f /pre-update

	# Run post-update if applicable
	if [ -f /post-update ]; then
		chmod +x /post-update
		echo "Running post-update script..."
		/post-update
		rm /post-update
	fi
}

start() {
	# Check for update file in /boot and install it if present
	if [ -f "/boot/$UPGRADE_FILE" ]; then
		echo "Found $UPGRADE_FILE on /boot, installing... "
		do_upgrade "/boot/$UPGRADE_FILE"
		[ $? -eq 0 ] && echo "OK" || echo "ERROR"
	fi

	# Keep checking for updates on USB drives
	while true; do
		for MOUNT_POINT in $(echo /media/usb[0-7] 2>/dev/null); do
			if mountpoint -q "$MOUNT_POINT"; then
				if [ -f "$MOUNT_POINT/$UPGRADE_FILE" ]; then
		echo "Found $UPGRADE_FILE on $MOUNT_POINT, installing... "
					do_upgrade "$MOUNT_POINT/$UPGRADE_FILE"
					[ $? -eq 0 ] && echo "OK" || echo "ERROR"
				fi
			fi
		done
		sleep 2
	done &
	echo $! > "$PIDFILE"
}

stop() {
	if [ -f "$PIDFILE" ]; then
		kill $(cat "$PIDFILE")
		rm -f "$PIDFILE"
	fi
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
		;;
esac

